// <auto-generated />
using System;
using FilmCollection.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    [Migration("20220202184210_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("FilmCollection.Models.Categories", b =>
                {
                    b.Property<int>("Categoryid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("Categoryid");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            Categoryid = 1,
                            CategoryName = "Action"
                        },
                        new
                        {
                            Categoryid = 2,
                            CategoryName = "Sci-Fi"
                        },
                        new
                        {
                            Categoryid = 3,
                            CategoryName = "Drama"
                        },
                        new
                        {
                            Categoryid = 4,
                            CategoryName = "Family"
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.FilmCollectionResponse", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoriesCategoryid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Categoryid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT")
                        .HasMaxLength(25);

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<short>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("MovieID");

                    b.HasIndex("CategoriesCategoryid");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Categoryid = 4,
                            Director = "Chris Williams",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Big Hero 6",
                            Year = (short)2014
                        },
                        new
                        {
                            MovieID = 2,
                            Categoryid = 2,
                            Director = "George Lucas",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "PG",
                            Title = "Star Wars: Episode IV - A New Hope",
                            Year = (short)1977
                        },
                        new
                        {
                            MovieID = 3,
                            Categoryid = 3,
                            Director = "Gus Vant Sant",
                            Edited = false,
                            LentTo = "",
                            Notes = "",
                            Rating = "R",
                            Title = "Good Will Hunting",
                            Year = (short)1997
                        });
                });

            modelBuilder.Entity("FilmCollection.Models.FilmCollectionResponse", b =>
                {
                    b.HasOne("FilmCollection.Models.Categories", "Categories")
                        .WithMany()
                        .HasForeignKey("CategoriesCategoryid");
                });
#pragma warning restore 612, 618
        }
    }
}
